---
title: Consumers & Community
---

We're commited to engaging and respecting the cancer community. Your
advocacy provides vital guidance in this research. 
We believe in collaboration and partnership so that in our research
there is *nothing about the community without the community*. We
believe this improves research and helps make sure it is work that is
relevant and useful.

#### About Involvement in Research

Right now, we are looking for people who currently have cancer or have
had cancer in the past or have cared for someone with cancer, such as
a partner or family member.

Our projects in cancer include developing and testing new treatments
to help people manage strong feelings, improve sleep, and reduce
tiredness or fatigue after cancer.

If having a voice in research around emotions, sleep, or fatigue in
cancer is something you might want to do, we would like to hear from
you and talk more about working together. Also, if you know anyone
else who may be interested, we would appreciate you passing on our
contact information to them.

----------------------------------------------------------------------

<!-- # Get Involved -->

<!-- If you are interested in joining our team as a consumer or community -->
<!-- member, read about the two roles we have below and  -->
<!-- fill out an <a href = "">expression of interest form</a>. -->
<!-- Someone from our team will then reach out to you. -->

<!-- #### Consumer and Community **Partners** -->

<!-- Becoming a consumer or community partner with us requires some -->
<!-- time. To partner with us, we ask that you be willing to commit to: -->

<!-- * Complete training about being a consumer or community representative -->
<!--   in research. This takes about 2-3 hours and can be completed at home -->
<!--   and over the phone. -->

<!-- * Meet for half a day in person at Monash University Clayton Campus -->
<!--   once per year -- about 4 hours per year. Catering will be provided -->
<!--   and parking provided or any parking expenses reimbursed. -->
  
<!-- * Join phone (or video) meetings 2-4 times per year. Each meeting may be -->
<!--   around 1 hour long, so about 2-4 hours per year. -->
  
<!-- In total, we expect this to take about 8 - 12 hours per year.  -->
<!-- In appreciation for that time, volunteers who persist with us through -->
<!-- the year will receive an  honorarium valued at $400 -->

<!-- #### Consumer and Community **Reviewers** -->

<!-- Becoming a consumer or community reviewer involves some training and a -->
<!-- very flexible schedule. As a reviewer, you would: -->

<!-- * Complete training about being a consumer or community representative -->
<!--   in research. This takes about 2-3 hours and can be completed at home -->
<!--   and over the phone. -->
  
<!-- * Review documents and materials. These would normally be emailed to -->
<!--   you. Some examples of documents that you might review and provide -->
<!--   input on are: -->
<!--     - a plain language summary of a project; -->
<!-- 	- questions we are thinking of asking people who take part in a -->
<!--       study; -->
<!-- 	- handouts or information we are thinking of giving to people in a -->
<!--       study; -->
<!-- 	- a presentation or newsletter we want to share with the public; -->
<!-- 	- an application for grant funding. -->
  
<!-- In total, we expect this to take about 4 - 8 hours per year.  -->
<!-- In appreciation for that time, volunteers who persist with us through -->
<!-- the year will receive an honorarium valued at $250. -->

<!-- ---------------------------------------------------------------------- -->

## Resources

#### Contact

If you have any questions, concerns or want to talk about any aspect
of your role as a consumer member of our team, reach out to Josh
<span class="fa fa-envelope"></span> joshua.wiley _at_ monash.edu.

#### Information for New Consumer and Community Members

Although developed for the United Kingdom, these guides have helpful
information for understanding what it means to be a consumer or
community member of a research team and help navigate the jargon used
in research.

* **Getting Started Guide**:
  https://www.invo.org.uk/wp-content/uploads/2019/10/Starting-Out-Revised-FINAL.pdf
  
* **Guide to Jargon**:
  https://www.invo.org.uk/wp-content/uploads/2011/12/PIP44jargonbuster.pdf 

#### Monash University Clayton Campus

Our team is based at Monash University Clayton Campus. You can find
directions on the map below.

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7400.802044166879!2d145.1337347219778!3d-37.911512923986855!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad66acbf64673b9%3A0xfaf9b169a587104!2sMonash%20University!5e0!3m2!1sen!2sau!4v1573094798089!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

