---
title: Joshua F. Wiley's CV
---


```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 

library(checkpoint); checkpoint("2019-01-25", scanForPackages = FALSE)
library(fontawesome)
library(readxl)
library(data.table)
library(rmarkdown)
library(scholar)
library(ggplot2)
library(plotly)

yearSincePhD <- round(as.numeric(
  difftime(Sys.Date(), as.Date("2015-03-24"),
           units = "days")/365.25), 1)

jwCites <- function() {
  ct <- get_citation_history("bRG3LSQAAAAJ")
  ct2 <- ct
  ct2$cites <- cumsum(ct2$cites)
  ct$Type <- "Yearly"
  ct2$Type <- "Cumulative"
  ct <- rbind(ct, ct2)

  ggplot(ct, aes(year, cites)) +
    geom_bar(stat = "identity") +
    ylab("Number of Citations") + 
    theme_classic() +
    theme(axis.title.x = element_blank()) + 
    facet_wrap(~ Type, scales = "free_y") + 
    coord_cartesian(expand=FALSE) +
    ggtitle("Google Scholar Citations")
}
citeplot <- tryCatch(jwCites(), error = function(e) ggplot() + ggtitle("Could not pull citations."))

pubs <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Publications")
pubs <- as.data.table(pubs)

tmp <- pubs[Type %in% c("Empirical", "Review"), FirstLast]
NFirstLast <- sum(tmp == 1)
NCoAuthor <- sum(tmp == 0)
NBooks <- nrow(pubs[Type %in% c("Book")])
NOther <- nrow(pubs[!Type %in% c("Empirical", "Review", "Book")])
rm(tmp)

prpubs <- pubs[Type %in% c("Empirical", "Review")]
prpubs[, Num := .N:1]

bpubs <- pubs[Type %in% c("Book", "Book Chapter")]
bpubs[, Num := .N:1]

epubs <- pubs[Type %in% c("Editorial")]
epubs[, Num := .N:1]

presentations <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Presentations")
presentations <- as.data.table(presentations)

leadabstracts <- presentations[FirstLast == 1 & Type != "Invited"]
leadabstracts[, Num := .N:1]

coabstracts <- presentations[FirstLast == 0 & Type != "Invited"]
coabstracts[, Num := .N:1]

invited <- presentations[FirstLast == 1 & Type == "Invited"]
invited[, Num := .N:1]

printPubs <- function(year, d) {
  paste(c(
    sprintf("`%s`", as.character(year)),
    "<ol>",
    paste(sprintf("<li value = %d>%s</li>", d[Year == year, Num], d[Year == year, Reference]),
          collapse = "\n"),
    "</ol>"), collapse = "\n")
}

students <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Students")
students <- as.data.table(students)[Status != "Withdrew"]

tmp <- students[Type %in% c("DPsych (Clinical)", "PhD (Clinical)", "PhD"), Primary]
NPrimary <- sum(tmp == 1)
NSecondary <- sum(tmp == 0)
rm(tmp)

students[, CVSummary := sprintf("%s %s | %d - %s | %s | %s supervisor",
                                GivenName, FamilyName, Started,
                                ifelse(Status == "Current", "current", Ended),
                                Type, ifelse(Primary == 1, "primary", "co"))]

dstudents <- students[Type %in%
                      c("DPsych (Clinical)", "PhD (Clinical)", "PhD")][
  order(-Started, -Type)]
dstudents[, Num := .N:1]
dstudents[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
dstudents <- paste(c("<ol>", dstudents$CVSummary, "</ol>"), collapse = "\n")

hstudents <- students[Type %in% c("Honours")][order(-Started)]
hstudents[, Num := .N:1]
hstudents[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
hstudents <- paste(c("<ol>", hstudents$CVSummary, "</ol>"), collapse = "\n")

teaching <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Teaching")
teaching <- as.data.table(teaching)[order(Level, -Ended, -Year, Role)]
teaching[, Num := .N:1]
teaching[, CVSummary := sprintf("%d - %s | %s | *%s* (%s) | %s",
        Year, Ended,
        Role,
        Title, Code,
        Organization)]

dteaching <- teaching[Level == "Doctoral"]
dteaching[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
dteaching <- paste(c("<ol>", dteaching$CVSummary, "</ol>"), collapse = "\n")

hteaching <- teaching[Level == "Honours"]
hteaching[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
hteaching <- paste(c("<ol>", hteaching$CVSummary, "</ol>"), collapse = "\n")

uteaching <- teaching[Level == "Undergraduate"]
uteaching[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
uteaching <- paste(c("<ol>", uteaching$CVSummary, "</ol>"), collapse = "\n")


grants <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Grants")
grants <- as.data.table(grants)[, Started := as.Date(Started)]
grants[, Ended := as.Date(Ended)]
grants <- grants[order(Status, -Started)]



grants[, CVSummary := sprintf("%d - %d | %s (%s)\nPI: %s\nTotal Value: %s (%s)\nRole: %s",
        format(Started, format = "%Y"),
        format(Ended, format = "%Y"),
        Number, Funder,
        formatC(Total, format="f", digits=0, big.mark=","), Currency,
        Role)]
grants[, Num := .N:1]

cgrants <- grants[Status == "Current"]
cgrants[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
cgrants <- paste(c("<ol>", cgrants$CVSummary, "</ol>"), collapse = "\n")

pgrants <- grants[Status == "Past"]
pgrants[, CVSummary := sprintf("<li value = %d>%s</li>", Num, CVSummary)]
pgrants <- paste(c("<ol>", pgrants$CVSummary, "</ol>"), collapse = "\n")


awards <- read_excel("~/OneDrive/WileyDossier/CV_Full.xlsx", sheet = "Awards")


summarystatement <- sprintf(
  "Lecturer at Monash University; **%0.1f** years post PhD; >$3 million AUD in grant funding; **%d** primary, **%d** co-supervised doctoral students; **2** Associate/Statistical editorial positions at journals; NHMRC panel member; **%d** first/last & **%d** co-author peer reviewed articles; **%d** books; **%d** other pubs; **%d** first/last & **%d** co-author peer reviewed abstracts; **%d** invited presentations; **6** software packages developed.",
  yearSincePhD,
  NPrimary, NSecondary,
  NFirstLast, NCoAuthor,
  NBooks, NOther,
  nrow(leadabstracts),
  nrow(coabstracts),
  nrow(invited))
                            


```

<br></br>

## <span class="fa fa-university"></span> EDUCATION

`2010 - 24 March 2015`
**Doctor of Philosophy** in Psychology (Health & Quantitative) from
the *University of California, Los Angeles*. 
Supervisor: Annette Stanton. Dissertation title: *Measurement of
Psychosocial Resources, Allostatic Load, and Their Relations*.
GPA: 3.96/4.00

`2010 - 2011`
**Master of Arts** in Psychology from the *University of California,
Los Angeles*. Supervisor: Annette Stanton.

`2006 - 2010`
**Bacher of Arts** with honors in Psychology from the *University of
California Riverside*. Supervisor: Howard Friedman. GPA: 3.95/4.00

`2002 - 2005`
**General Coursework** at *Riverside Community College*. Undeclared
major. GPA: 4.00/4.00

<br></br>

## Academic Summary

`r summarystatement`

<br></br>

## <span class="fa fa-building"></span> WORK EXPERIENCE

`June 2016 - present`
**Lecturer**, Monash Institute of Cognitive and Clinical
Neurosciences, School of Psychological Sciences Lecturer (tenure-track
Assistant Professor)

`December 2016 - 2019`
**Senior advisor**, Elkhart Group LLC.

`January 2015 - June 2016`
**Post Doctoral Fellow**, Australia Catholic University

`July 2013 - March 2015`
**Graduate Student Researcher**, My Year After Cancer Study (1R01 CA133081)

`June 2013 - December 2016`
**Partner and Data Scientist**, Elkhart Group Ltd.

`August 2011 - June 2013`
**Programmer analyst**, IDRE Statistical Consulting Group 

`September 2008 - June 2010`
**Research Assistant and Honors Student**, Professor Howard Friedman's
Laboratory at the University of California, Riverside

<br></br>

-------------------------------------------

## <span class="fa fa-book-open"></span> PUBLICATIONS

`r ggplotly(citeplot)`

### <span class="fa fa-file-alt"></span> Peer-Reviewed Articles

`r paste(unlist(lapply(unique(prpubs$Year), printPubs, d = prpubs)), collapse = "\n")`

### <span class="fa fa-book"></span> Books and Book Chapters

`r paste(unlist(lapply(unique(bpubs$Year), printPubs, d = bpubs)), collapse = "\n")`

### <span class="fa fa-file-contract"></span> Commentaries and Letters to the Editor

`r paste(unlist(lapply(unique(epubs$Year), printPubs, d = epubs)), collapse = "\n")`

<br></br>

-------------------------------------------

## <span class="fa fa-chalkboard-teacher"></span> ABSTRACTS, PRESENTATIONS, & SYMPOSIA

### First or Last Author

`r paste(unlist(lapply(unique(leadabstracts$Year), printPubs, d = leadabstracts)), collapse = "\n")`

### Co-Author

`r paste(unlist(lapply(unique(coabstracts$Year), printPubs, d = coabstracts)), collapse = "\n")`

### Invited

`r paste(unlist(lapply(unique(invited$Year), printPubs, d = invited)), collapse = "\n")`


## <span class="fa fa-dollar-sign"></span> GRANTS

`Current`
`r cgrants`

`Past`
`r pgrants`

## <span class="fa fa-university"></span> TEACHING

`Doctoral`
`r dteaching`

`Honours`
`r hteaching`

`Undergraduate`
`r uteaching`


## <span class="fa fa-graduation-cap"></span> STUDENTS

`Doctoral`
`r dstudents`

`Honours`
`r hstudents`
